# Generated by Django 5.1.6 on 2025-02-21 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('plan_state', models.CharField(choices=[('待开始', 'PENDING'), ('进行中', 'SHIPPED'), ('已完成', 'DELIVERED')], default='待开始', max_length=3)),
                ('plan_type', models.CharField(blank=True, choices=[('康复护理', 'RECOVER'), ('日常护理', 'DAILY')], max_length=4, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('staff_id', models.IntegerField()),
                ('plan_satisfaction', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('nutrition_info', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_description', models.CharField(max_length=255)),
                ('ingredient_amount', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('nutrition', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSMS',
            fields=[
                ('SMS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('SMS', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(db_comment='客户id', primary_key=True, serialize=False)),
                ('care_level', models.IntegerField(blank=True, null=True)),
                ('care_demand', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=255, null=True)),
                ('dietary_preference', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlans',
            fields=[
                ('diet_plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('diet_date', models.DateField()),
                ('staff_id', models.IntegerField()),
                ('nutrition_requirements', models.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('vital_signs', models.JSONField(blank=True, null=True)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.CharField(blank=True, max_length=1024, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
            ],
        ),
        migrations.CreateModel(
            name='PlanGoals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_state', models.CharField(choices=[('未达成', 'UNDONE'), ('已达成', 'DONE')], default='未达成', max_length=3)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.careplans')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('早餐', 'BREAKFAST'), ('午餐', 'LUNCH'), ('晚餐', 'DINNER')], max_length=2, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dietplans')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodrecipes')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodrecipes')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequirements',
            fields=[
                ('requirement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('min_staff', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.shifttemplates')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('待确认', 'PENDING'), ('已预约', 'SHIPPED'), ('已结束', 'DELIVERED'), ('已取消', 'CANCELLED')], default='待确认', max_length=3)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.careplans')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.services')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSchedules',
            fields=[
                ('shift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('week_num', models.IntegerField(blank=True, null=True)),
                ('assigned_date', models.DateField()),
                ('actual_start', models.DateTimeField()),
                ('actual_end', models.DateTimeField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.shifttemplates')),
            ],
        ),
    ]
