# Generated by Django 5.1.6 on 2025-02-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_careplans_foodrecipes_ingredients_roles_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='api.roles'),
            preserve_default=False,
        ),
    ]
