# Generated by Django 5.1.6 on 2025-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='emergency_contact',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='gender',
            field=models.CharField(choices=[('男', 'MALE'), ('女', 'FEMALE')], default='男', max_length=10),
        ),
    ]
