# Generated by Django 5.1.6 on 2025-02-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clients_birth_date_clients_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetrics',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
            preserve_default=False,
        ),
    ]
