# Generated by Django 5.1.6 on 2025-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_healthmetrics_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shiftrequirements',
            name='requirement_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
