# Generated by Django 5.1.6 on 2025-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_services_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
