# Generated by Django 5.1.6 on 2025-02-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_services_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplans',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='careplans',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
    ]
