# Generated by Django 5.1.6 on 2025-02-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_careplans_client_id_alter_careplans_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplans',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='careplans',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
    ]
