# Generated by Django 5.1.6 on 2025-02-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_careplans_staff_id_careplans_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplans',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.clients'),
            preserve_default=False,
        ),
    ]
