# Generated by Django 5.1.6 on 2025-03-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_careplans_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffschedules',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='staffschedules',
            name='actual_start',
        ),
        migrations.RemoveField(
            model_name='staffschedules',
            name='week_num',
        ),
        migrations.DeleteModel(
            name='ShiftRequirements',
        ),
    ]
