# Generated by Django 5.1.6 on 2025-03-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_staffschedules_actual_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedules',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
    ]
