# Generated by Django 5.1.6 on 2025-03-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_staffschedules_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffschedules',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
            preserve_default=False,
        ),
    ]
