# Generated by Django 5.1.6 on 2025-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_staffschedules_staff_id_staffschedules_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedules',
            name='shift_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
