# Generated by Django 5.1.6 on 2025-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_ingredients_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplans',
            name='nutrition_taken',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
