# Generated by Django 5.1.6 on 2025-03-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dietplans_nutrition_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecipe',
            name='type',
        ),
        migrations.AddField(
            model_name='dietplans',
            name='type',
            field=models.CharField(blank=True, choices=[('早餐', 'BREAKFAST'), ('午餐', 'LUNCH'), ('晚餐', 'DINNER')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dietplans',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='dietplans',
            unique_together={('diet_date', 'type', 'client')},
        ),
    ]
