# Generated by Django 5.1.6 on 2025-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_planrecipe_type_dietplans_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dietplans',
            unique_together={('diet_date', 'client')},
        ),
        migrations.AddField(
            model_name='planrecipe',
            name='type',
            field=models.CharField(blank=True, choices=[('早餐', 'BREAKFAST'), ('午餐', 'LUNCH'), ('晚餐', 'DINNER')], max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='dietplans',
            name='type',
        ),
    ]
