# Generated by Django 5.1.6 on 2025-03-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_dietplans_unique_together_planrecipe_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplans',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='dietplans',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
    ]
