# Generated by Django 5.1.6 on 2025-03-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_dietplans_staff_id_dietplans_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSMS',
        ),
        migrations.AlterUniqueTogether(
            name='staffschedules',
            unique_together={('staff', 'assigned_date')},
        ),
    ]
