# Generated by Django 5.1.6 on 2025-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_usersms_alter_staffschedules_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_reset',
            field=models.BooleanField(default=False),
        ),
    ]
