# Generated by Django 5.1.6 on 2025-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplans',
            name='smart_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
