# Generated by Django 5.1.6 on 2025-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_dietplans_smart_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='income_range',
            field=models.CharField(choices=[('已婚', 'MARRIED'), ('未婚', 'SINGLE'), ('离婚', 'DIVORCED'), ('丧偶', 'WIDOWED'), ('分居', 'SEPARATED')], default='3000-6000元/月', max_length=20),
        ),
        migrations.AddField(
            model_name='clients',
            name='marital',
            field=models.CharField(choices=[('已婚', 'MARRIED'), ('未婚', 'SINGLE'), ('离婚', 'DIVORCED'), ('丧偶', 'WIDOWED'), ('分居', 'SEPARATED')], default='未婚', max_length=10),
        ),
    ]
