# Generated by Django 5.1.6 on 2025-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_clients_income_range_clients_marital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='income_range',
            field=models.CharField(choices=[('小于3000元/月', 'LOW'), ('3000-6000元/月', 'MID'), ('大于6000元/月', 'HIGH')], default='3000-6000元/月', max_length=20),
        ),
    ]
