# Generated by Django 5.1.6 on 2025-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_clients_income_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetrics',
            name='mets_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
