# Generated by Django 5.1.6 on 2025-03-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_healthmetrics_mets_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetrics',
            name='smart_assessment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
