# Generated by Django 5.1.6 on 2025-04-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_healthmetrics_smart_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetrics',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
    ]
