from . import views
from django.urls import path

urlpatterns = [
    path('users/', views.user_list, name='user-list'),
    path('users/<int:pk>/', views.user_detail, name='user-detail'),
    path('users/info/', views.get_user_info, name='user-info'),
    path('users/login/', views.login, name='login'),
    path('users/register/', views.register, name='register'),
    path('users/logout/', views.user_logout, name='user_logout'),  # 登出接口路由
    path('users/update/', views.edit_user, name='edit_user'),  # 用户个人更新用户数据
    path('users/password_reset/<int:pk>/', views.reset_password, name='reset_password'),   # 管理员重置用户密码
    path('users/deny_reset/<int:pk>', views.reset_deny, name='reset_deny'),   # 管理员拒绝重置密码申请
    path('users/password_update/', views.update_password, name='update_password'),  # 用户个人更新个人密码
    path('users/register/admin/', views.register_admin, name='register_user_admin'),  # 管理员注册用户接口
    path('users/reset_list/', views.get_reset_list, name='reset_list'),
    path('users/put_reset/<str:username>/', views.put_reset, name='put_reset'),
    path('users/change_active/<int:pk>/', views.update_user_active, name='update_user_active'),
    path('users/staff/', views.get_all_staff, name="get_all_staff"),
    path('staff/available/', views.available_staff, name="available_staff"),
    path('clients/', views.get_clients, name='clients-list'),  # 使用
    path('clients/<int:client_id>/', views.get_client_details, name="clients-detail"),   # 根据客户id查询客户档案
    path('clients/update/<int:client_id>/', views.update_client, name='update_client'),  # 管理员和员工更新客户档案
    path('metrics/update/staff/', views.update_client_health_metrics, name='update_client_health_metrics'),  # 员工或管理员更新客户健康指标
    path('metrics/create/staff/', views.create_client_health_metrics, name='create_client_health_metrics'),  # 员工或管理员创建客户健康指标
    path('metrics/get/<int:client_id>/', views.get_client_health_metrics, name='get_client_health_metrics'),  # 使用
    path('metrics/delete/<int:pk>/', views.delete_client_health_metrics, name='delete_client_health_metrics'),
    path('plans/get/<int:client_id>/', views.get_client_plans, name='get_client_plans'),  # 员工或管理员查询计划
    path('plans/create/', views.create_care_plans, name='create_care_plans'),
    path('plans/delete/<int:pk>/', views.delete_care_plans, name='delete_care_plans'),
    path('plans/update/', views.update_care_plans, name='update_care_plans'),
    path('services/', views.get_services, name='services-list'),  # 查询所有服务
    path('services/create/', views.create_service, name='create_service'),
    path('services/update/', views.update_service, name="update_service"),
    path('services/delete/<int:pk>/', views.delete_service, name="delete_service"),
    path('appointments/', views.get_appointments, name='appointments-list'),
    path('appointments/<int:client_id>/', views.get_client_appointments, name='get_client_appointments'),
    path('appointments/delete/<int:pk>/', views.delete_appointments, name='delete_appointments'),
    path('appointments/create/<int:client_id>/', views.create_appointment, name='create_appointment'),
    path('appointments/update/<int:client_id>/', views.update_appointment, name='update_client_appointment'),
    path('appointments/all/', views.get_all_appointments, name='get_all_appointments'),  # 使用
    path('goals/create/', views.create_goal, name='create_goal'),
    path('goals/update/', views.update_goal, name="update_goal"),
    path('goals/delete/<int:pk>/', views.delete_goal, name='delete_goal'),
    path('plans/get_appointments/<int:plan_id>/', views.get_plan_appointments, name="get_plan_appointments"),
    path('plans/get_goals/<int:plan_id>/', views.get_plan_goals, name="get_plan_goals"),
    path('plans/score/<int:client_id>/', views.score_plan, name="score_plan"),
    path('plans/get_report/<int:plan_id>/', views.get_plan_progress, name="get_plan_progress"),
    path('templates/create/', views.create_shift_template, name='create_shift_template'),
    path('templates/update/', views.update_shift_template, name="update_shift_template"),
    path('templates/delete/<int:pk>/', views.delete_shift_template, name="delete_shift_template"),
    path('templates/get/', views.get_shift_template, name="get_shift_template"),
    path('roles/create/', views.create_role, name="create_role"),
    path('roles/update/', views.update_role, name="update_role"),
    path('roles/get/', views.get_role, name="get_role"),
    path('schedules/create/', views.create_staff_schedule, name="create_staff_schedule"),
    path('schedules/update/', views.update_staff_schedule, name="update_staff_schedule"),
    path('schedules/get/', views.get_staff_schedule, name="get_staff_schedule"),
    path('schedules/get/after/<int:staff_id>/', views.get_staff_schedule_after_today, name="get_staff_schedule_after_today"),
    path('schedules/get/<int:staff_id>/', views.get_staff_schedule_certain, name="get_staff_schedule_certain"),
    path('schedules/delete/<int:pk>/', views.delete_staff_schedule, name="delete_staff_schedule"),
    path('schedules/get/<str:date>/', views.get_schedules_by_date, name='get_schedules_by_date'),
    path('schedules/get/<str:date>/<int:staff_id>/', views.get_staff_schedule_by_date, name='get_staff_schedule_by_date'),
    path('ingredients/', views.get_ingredient, name="get_ingredient"),
    path('ingredients/create/', views.create_ingredient, name="create_ingredient"),
    path('ingredients/update/', views.update_ingredient, name="update_ingredient"),
    path('ingredients/delete/<int:pk>/', views.delete_ingredient, name="delete_ingredient"),
    path('recipes/', views.get_recipe, name='get_recipe'),
    path('recipes/create/', views.create_recipe, name='create_recipe'),
    path('recipes/update/', views.update_recipe, name='update_recipe'),
    path('recipes/delete/<int:pk>/', views.delete_recipe, name='delete_recipe'),
    path('recipes/avoidance/', views.get_recipe_by_avoidance, name='get_recipe_by_avoidance'),
    path('recipes/preference/', views.get_recipe_by_preference, name='get_recipe_by_preference'),
    path('diet_plans/<int:client_id>/', views.get_diet_plan, name='get_diet_plan'),
    path('diet_plans/certain_day/', views.get_certain_day_diet_plan, name='get_certain_day_diet_plan'),
    path('diet_plans/update/', views.update_diet_plan, name='update_diet_plan'),
    path('diet_plans/delete/', views.delete_diet_plan, name='delete_diet_plan'),
    path('diet_plans/delete_entire/<int:diet_plan_id>/', views.delete_entire_diet_plan, name='delete_entire_diet_plan'),
    path('diet_plans/update_fields/<int:diet_plan_id>/', views.update_diet_plan_fields, name='update_diet_plan_fields'),
    path('diet_plans/create_record/', views.create_diet_plan_record, name='create_diet_plan_record'),
    path('notifications/', views.get_notifications, name='get_notifications'),  # 使用
    path('notifications/<int:pk>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('plans/all/', views.get_all_plans, name='get_all_plans'),  # 使用
    path('diet_plans/generate_diet_recommendation/<int:diet_plan_id>/', views.generate_diet_recommendation, name='generate_diet_recommendation'),
    path('metrics/generate_metrics_assessment/<int:metric_id>/', views.generate_metrics_assessment, name='generate_metrics_assessment'),
]