"""
Django settings for smart_care project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MODELS_DIR = BASE_DIR / 'models'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+)inylr$9n@i1g4yl--ojv1lxa2gl%%996o(4^$*tggcq2p1y)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "api.apps.ApiConfig",
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'django_celery_beat',
    'django_eventstream',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'smart_care.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_care.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 MySQL 数据库
        'NAME': 'smart_care',          # 数据库名称
        'USER': 'root',         # MySQL 用户名
        'PASSWORD': 'liu13693473867',     # MySQL 密码
        'HOST': 'localhost',                   # MySQL 服务器地址，如果在本地运行为 localhost
        'PORT': '3306',                        # MySQL 端口（默认是 3306）
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 跨域配置
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # 允许的前端地址
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',  # Vue 开发服务器地址
]

# session配置
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # 使用数据库（db）存储 session
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 2  # 会话过期时间（单位：秒）, 默认两周
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 浏览器关闭时会话不会失效

# user表配置
AUTH_USER_MODEL = 'api.Users'


# redis 配置
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',  # Redis 服务器地址和端口
        'TIMEOUT': '3600',  # 默认缓存失效时间为为1h
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Celery 配置
CELERY_WORKER_POOL = 'solo'
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'  # 设置时区为中国

CELERY_BEAT_SCHEDULE = {
    'send-admin-notification': {
        'task': 'api.tasks.send_admin_notification',
        'schedule': crontab(minute=0),  # 每小时整点执行
    },
    'send-appointment-reminders': {
        'task': 'api.tasks.send_appointment_reminders',
        'schedule': crontab(minute='*/5'),  # 每5分钟执行一次
    },
    'send-care-plan-reminders': {
        'task': 'api.tasks.send_care_plan_reminders',
        'schedule': crontab(hour=6, minute=0),  # 每天6:00执行
    },
    'clean-old-notifications': {
        'task': 'api.tasks.clean_old_notifications',
        'schedule': crontab(hour=0, minute=0),  # 每天凌晨执行
    },
}


# django-eventstream 配置
# DJANGO_EVENTSTREAM_ALLOW_ORIGIN = "*"
# DJANGO_EVENTSTREAM_HTTP_METHODS = ["GET", "OPTIONS"]
# EVENTSTREAM_CHANNELS = { 'notification': ['notification'] }
# EVENTSTREAM_CHANNELS = {
#     'notification': lambda request, channel: channel.startswith("notification")
# }
